spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wedding_host_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ggzst321
    type: com.zaxxer.hikari.HikariDataSource
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      max-active: 10


mybatis-plus:
  type-aliases-package: com.quxue.wedding_host.pojo,com.quxue.wedding_host.vo
  global-config:
    db-config:
      #全局删除字段
      logic-delete-field: status
      logic-delete-value: 0
      logic-not-delete-value: 1


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #standand 标准输出

minio:
  endpoint: http://101.34.204.193:9000 #服务器地址
  access-key: minioadmin #账号
  secret-key: minioadmin #密码
  bucket-name: harusame #文件上传的桶

